import type { Metadata } from "next";
import { Share_Tech } from "next/font/google";
import "./globals.css";

// Configure Share Tech font
const shareTech = Share_Tech({
  weight: "400", // Define the weight explicitly
  subsets: ["latin"], // Subsets must be in an array
  variable: "--font-share-tech", // Use the variable for CSS
  preload: true, // Optionally preload the font
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${shareTech.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
